branch-defaults:
  default:
    environment: Env-Udagramapi
    group_suffix: null
environment-defaults:
  Uadcityfullstack-env:
    branch: null
    repository: null
  Udacityfullstack-env:
    branch: null
    repository: null
  Udagramapi-env:
    branch: null
    repository: null
global:
  application_name: udagram-api
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
